// Auto-generated by scripts/generate_param_compat.go
// DO NOT EDIT MANUALLY

#pragma once
#include <map>
#include <string>

namespace mihomo {

struct ParamCompatInfo {
    bool supported;
    std::string type;
    bool hardcoded;  // true if Mihomo hardcodes this parameter
};

const std::map<std::string, std::map<std::string, ParamCompatInfo>> PARAM_COMPAT = {
    // Protocol: anytls
    {"anytls", {
        {"alpn", {true, "array", false}}, // anytls
        {"certificate", {true, "string", false}}, // anytls
        {"client-fingerprint", {true, "string", false}}, // anytls
        {"dialer-proxy", {true, "string", false}}, // BasicOption
        {"ech-opts", {true, "string", false}}, // anytls
        {"fingerprint", {true, "string", false}}, // anytls
        {"idle-session-check-interval", {true, "int", false}}, // anytls
        {"idle-session-timeout", {true, "int", false}}, // anytls
        {"interface-name", {true, "string", false}}, // BasicOption
        {"ip-version", {true, "string", false}}, // BasicOption
        {"min-idle-session", {true, "int", false}}, // anytls
        {"mptcp", {true, "bool", false}}, // BasicOption
        {"name", {true, "string", false}}, // anytls
        {"password", {true, "string", false}}, // anytls
        {"port", {true, "int", false}}, // anytls
        {"private-key", {true, "string", false}}, // anytls
        {"routing-mark", {true, "int", false}}, // BasicOption
        {"server", {true, "string", false}}, // anytls
        {"skip-cert-verify", {true, "bool", false}}, // anytls
        {"sni", {true, "string", false}}, // anytls
        {"tfo", {true, "bool", false}}, // BasicOption
        {"udp", {true, "bool", true}}, // anytls [HARDCODED]
    }},
    // Protocol: http
    {"http", {
        {"certificate", {true, "string", false}}, // http
        {"dialer-proxy", {true, "string", false}}, // BasicOption
        {"fingerprint", {true, "string", false}}, // http
        {"headers", {true, "object", false}}, // http
        {"interface-name", {true, "string", false}}, // BasicOption
        {"ip-version", {true, "string", false}}, // BasicOption
        {"mptcp", {true, "bool", false}}, // BasicOption
        {"name", {true, "string", false}}, // http
        {"password", {true, "string", false}}, // http
        {"port", {true, "int", false}}, // http
        {"private-key", {true, "string", false}}, // http
        {"routing-mark", {true, "int", false}}, // BasicOption
        {"server", {true, "string", false}}, // http
        {"skip-cert-verify", {true, "bool", true}}, // http [HARDCODED]
        {"sni", {true, "string", false}}, // http
        {"tfo", {true, "bool", false}}, // BasicOption
        {"tls", {true, "bool", true}}, // http [HARDCODED]
        {"username", {true, "string", false}}, // http
    }},
    // Protocol: https
    {"https", {
        {"certificate", {true, "string", false}}, // https
        {"dialer-proxy", {true, "string", false}}, // BasicOption
        {"fingerprint", {true, "string", false}}, // https
        {"headers", {true, "object", false}}, // https
        {"interface-name", {true, "string", false}}, // BasicOption
        {"ip-version", {true, "string", false}}, // BasicOption
        {"mptcp", {true, "bool", false}}, // BasicOption
        {"name", {true, "string", false}}, // https
        {"password", {true, "string", false}}, // https
        {"port", {true, "int", false}}, // https
        {"private-key", {true, "string", false}}, // https
        {"routing-mark", {true, "int", false}}, // BasicOption
        {"server", {true, "string", false}}, // https
        {"skip-cert-verify", {true, "bool", false}}, // https
        {"sni", {true, "string", false}}, // https
        {"tfo", {true, "bool", false}}, // BasicOption
        {"tls", {true, "bool", false}}, // https
        {"username", {true, "string", false}}, // https
    }},
    // Protocol: hy2
    {"hy2", {
        {"alpn", {true, "array", false}}, // hy2
        {"certificate", {true, "string", false}}, // hy2
        {"cwnd", {true, "int", false}}, // hy2
        {"dialer-proxy", {true, "string", false}}, // BasicOption
        {"down", {true, "string", false}}, // hy2
        {"ech-opts", {true, "string", false}}, // hy2
        {"fingerprint", {true, "string", false}}, // hy2
        {"hop-interval", {true, "int", false}}, // hy2
        {"initial-connection-receive-window", {true, "int", false}}, // hy2
        {"initial-stream-receive-window", {true, "int", false}}, // hy2
        {"interface-name", {true, "string", false}}, // BasicOption
        {"ip-version", {true, "string", false}}, // BasicOption
        {"max-connection-receive-window", {true, "int", false}}, // hy2
        {"max-stream-receive-window", {true, "int", false}}, // hy2
        {"mptcp", {true, "bool", false}}, // BasicOption
        {"name", {true, "string", false}}, // hy2
        {"obfs", {true, "string", false}}, // hy2
        {"obfs-password", {true, "string", false}}, // hy2
        {"password", {true, "string", false}}, // hy2
        {"port", {true, "int", false}}, // hy2
        {"ports", {true, "string", false}}, // hy2
        {"private-key", {true, "string", false}}, // hy2
        {"routing-mark", {true, "int", false}}, // BasicOption
        {"server", {true, "string", false}}, // hy2
        {"skip-cert-verify", {true, "bool", false}}, // hy2
        {"sni", {true, "string", false}}, // hy2
        {"tfo", {true, "bool", false}}, // BasicOption
        {"udp-mtu", {true, "int", false}}, // hy2
        {"up", {true, "string", false}}, // hy2
    }},
    // Protocol: hysteria
    {"hysteria", {
        {"alpn", {true, "array", false}}, // hysteria
        {"auth", {true, "string", false}}, // hysteria
        {"auth-str", {true, "string", false}}, // hysteria
        {"certificate", {true, "string", false}}, // hysteria
        {"dialer-proxy", {true, "string", false}}, // BasicOption
        {"disable-mtu-discovery", {true, "bool", false}}, // hysteria
        {"down", {true, "string", false}}, // hysteria
        {"down-speed", {true, "int", false}}, // hysteria
        {"ech-opts", {true, "string", false}}, // hysteria
        {"fast-open", {true, "bool", false}}, // hysteria
        {"fingerprint", {true, "string", false}}, // hysteria
        {"hop-interval", {true, "int", false}}, // hysteria
        {"interface-name", {true, "string", false}}, // BasicOption
        {"ip-version", {true, "string", false}}, // BasicOption
        {"mptcp", {true, "bool", false}}, // BasicOption
        {"name", {true, "string", false}}, // hysteria
        {"obfs", {true, "string", false}}, // hysteria
        {"obfs-protocol", {true, "string", false}}, // hysteria
        {"port", {true, "int", false}}, // hysteria
        {"ports", {true, "string", false}}, // hysteria
        {"private-key", {true, "string", false}}, // hysteria
        {"protocol", {true, "string", false}}, // hysteria
        {"recv-window", {true, "int", false}}, // hysteria
        {"recv-window-conn", {true, "int", false}}, // hysteria
        {"routing-mark", {true, "int", false}}, // BasicOption
        {"server", {true, "string", false}}, // hysteria
        {"skip-cert-verify", {true, "bool", false}}, // hysteria
        {"sni", {true, "string", false}}, // hysteria
        {"tfo", {true, "bool", false}}, // BasicOption
        {"up", {true, "string", false}}, // hysteria
        {"up-speed", {true, "int", false}}, // hysteria
    }},
    // Protocol: hysteria2
    {"hysteria2", {
        {"alpn", {true, "array", false}}, // hysteria2
        {"certificate", {true, "string", false}}, // hysteria2
        {"cwnd", {true, "int", false}}, // hysteria2
        {"dialer-proxy", {true, "string", false}}, // BasicOption
        {"down", {true, "string", false}}, // hysteria2
        {"ech-opts", {true, "string", false}}, // hysteria2
        {"fingerprint", {true, "string", false}}, // hysteria2
        {"hop-interval", {true, "int", false}}, // hysteria2
        {"initial-connection-receive-window", {true, "int", false}}, // hysteria2
        {"initial-stream-receive-window", {true, "int", false}}, // hysteria2
        {"interface-name", {true, "string", false}}, // BasicOption
        {"ip-version", {true, "string", false}}, // BasicOption
        {"max-connection-receive-window", {true, "int", false}}, // hysteria2
        {"max-stream-receive-window", {true, "int", false}}, // hysteria2
        {"mptcp", {true, "bool", false}}, // BasicOption
        {"name", {true, "string", false}}, // hysteria2
        {"obfs", {true, "string", false}}, // hysteria2
        {"obfs-password", {true, "string", false}}, // hysteria2
        {"password", {true, "string", false}}, // hysteria2
        {"port", {true, "int", true}}, // hysteria2 [HARDCODED]
        {"ports", {true, "string", false}}, // hysteria2
        {"private-key", {true, "string", false}}, // hysteria2
        {"routing-mark", {true, "int", false}}, // BasicOption
        {"server", {true, "string", false}}, // hysteria2
        {"skip-cert-verify", {true, "bool", false}}, // hysteria2
        {"sni", {true, "string", false}}, // hysteria2
        {"tfo", {true, "bool", false}}, // BasicOption
        {"udp-mtu", {true, "int", false}}, // hysteria2
        {"up", {true, "string", false}}, // hysteria2
    }},
    // Protocol: socks
    {"socks", {
        {"certificate", {true, "string", false}}, // socks
        {"dialer-proxy", {true, "string", false}}, // BasicOption
        {"fingerprint", {true, "string", false}}, // socks
        {"interface-name", {true, "string", false}}, // BasicOption
        {"ip-version", {true, "string", false}}, // BasicOption
        {"mptcp", {true, "bool", false}}, // BasicOption
        {"name", {true, "string", false}}, // socks
        {"password", {true, "string", false}}, // socks
        {"port", {true, "int", false}}, // socks
        {"private-key", {true, "string", false}}, // socks
        {"routing-mark", {true, "int", false}}, // BasicOption
        {"server", {true, "string", false}}, // socks
        {"skip-cert-verify", {true, "bool", false}}, // socks
        {"tfo", {true, "bool", false}}, // BasicOption
        {"tls", {true, "bool", false}}, // socks
        {"udp", {true, "bool", false}}, // socks
        {"username", {true, "string", false}}, // socks
    }},
    // Protocol: socks5
    {"socks5", {
        {"certificate", {true, "string", false}}, // socks5
        {"dialer-proxy", {true, "string", false}}, // BasicOption
        {"fingerprint", {true, "string", false}}, // socks5
        {"interface-name", {true, "string", false}}, // BasicOption
        {"ip-version", {true, "string", false}}, // BasicOption
        {"mptcp", {true, "bool", false}}, // BasicOption
        {"name", {true, "string", false}}, // socks5
        {"password", {true, "string", false}}, // socks5
        {"port", {true, "int", false}}, // socks5
        {"private-key", {true, "string", false}}, // socks5
        {"routing-mark", {true, "int", false}}, // BasicOption
        {"server", {true, "string", false}}, // socks5
        {"skip-cert-verify", {true, "bool", false}}, // socks5
        {"tfo", {true, "bool", false}}, // BasicOption
        {"tls", {true, "bool", false}}, // socks5
        {"udp", {true, "bool", false}}, // socks5
        {"username", {true, "string", false}}, // socks5
    }},
    // Protocol: socks5h
    {"socks5h", {
        {"certificate", {true, "string", false}}, // socks5h
        {"dialer-proxy", {true, "string", false}}, // BasicOption
        {"fingerprint", {true, "string", false}}, // socks5h
        {"interface-name", {true, "string", false}}, // BasicOption
        {"ip-version", {true, "string", false}}, // BasicOption
        {"mptcp", {true, "bool", false}}, // BasicOption
        {"name", {true, "string", false}}, // socks5h
        {"password", {true, "string", false}}, // socks5h
        {"port", {true, "int", false}}, // socks5h
        {"private-key", {true, "string", false}}, // socks5h
        {"routing-mark", {true, "int", false}}, // BasicOption
        {"server", {true, "string", false}}, // socks5h
        {"skip-cert-verify", {true, "bool", false}}, // socks5h
        {"tfo", {true, "bool", false}}, // BasicOption
        {"tls", {true, "bool", false}}, // socks5h
        {"udp", {true, "bool", false}}, // socks5h
        {"username", {true, "string", false}}, // socks5h
    }},
    // Protocol: ss
    {"ss", {
        {"cipher", {true, "string", false}}, // ss
        {"client-fingerprint", {true, "string", false}}, // ss
        {"dialer-proxy", {true, "string", false}}, // BasicOption
        {"interface-name", {true, "string", false}}, // BasicOption
        {"ip-version", {true, "string", false}}, // BasicOption
        {"mptcp", {true, "bool", false}}, // BasicOption
        {"name", {true, "string", false}}, // ss
        {"password", {true, "string", false}}, // ss
        {"plugin", {true, "string", true}}, // ss [HARDCODED]
        {"plugin-opts", {true, "object", false}}, // ss
        {"port", {true, "int", false}}, // ss
        {"routing-mark", {true, "int", false}}, // BasicOption
        {"server", {true, "string", false}}, // ss
        {"tfo", {true, "bool", false}}, // BasicOption
        {"udp", {true, "bool", true}}, // ss [HARDCODED]
        {"udp-over-tcp", {true, "bool", true}}, // ss [HARDCODED]
        {"udp-over-tcp-version", {true, "int", false}}, // ss
    }},
    // Protocol: ssr
    {"ssr", {
        {"cipher", {true, "string", false}}, // ssr
        {"dialer-proxy", {true, "string", false}}, // BasicOption
        {"interface-name", {true, "string", false}}, // BasicOption
        {"ip-version", {true, "string", false}}, // BasicOption
        {"mptcp", {true, "bool", false}}, // BasicOption
        {"name", {true, "string", false}}, // ssr
        {"obfs", {true, "string", false}}, // ssr
        {"obfs-param", {true, "string", false}}, // ssr
        {"password", {true, "string", false}}, // ssr
        {"port", {true, "int", false}}, // ssr
        {"protocol", {true, "string", false}}, // ssr
        {"protocol-param", {true, "string", false}}, // ssr
        {"routing-mark", {true, "int", false}}, // BasicOption
        {"server", {true, "string", false}}, // ssr
        {"tfo", {true, "bool", false}}, // BasicOption
        {"udp", {true, "bool", true}}, // ssr [HARDCODED]
    }},
    // Protocol: trojan
    {"trojan", {
        {"alpn", {true, "array", false}}, // trojan
        {"certificate", {true, "string", false}}, // trojan
        {"client-fingerprint", {true, "string", false}}, // trojan
        {"dialer-proxy", {true, "string", false}}, // BasicOption
        {"ech-opts", {true, "string", false}}, // trojan
        {"fingerprint", {true, "string", false}}, // trojan
        {"grpc-opts", {true, "string", false}}, // trojan
        {"interface-name", {true, "string", false}}, // BasicOption
        {"ip-version", {true, "string", false}}, // BasicOption
        {"mptcp", {true, "bool", false}}, // BasicOption
        {"name", {true, "string", false}}, // trojan
        {"network", {true, "string", false}}, // trojan
        {"password", {true, "string", false}}, // trojan
        {"port", {true, "int", false}}, // trojan
        {"private-key", {true, "string", false}}, // trojan
        {"reality-opts", {true, "string", false}}, // trojan
        {"routing-mark", {true, "int", false}}, // BasicOption
        {"server", {true, "string", false}}, // trojan
        {"skip-cert-verify", {true, "bool", false}}, // trojan
        {"sni", {true, "string", false}}, // trojan
        {"ss-opts", {true, "string", false}}, // trojan
        {"tfo", {true, "bool", false}}, // BasicOption
        {"udp", {true, "bool", true}}, // trojan [HARDCODED]
        {"ws-opts", {true, "string", false}}, // trojan
    }},
    // Protocol: tuic
    {"tuic", {
        {"alpn", {true, "array", false}}, // tuic
        {"certificate", {true, "string", false}}, // tuic
        {"congestion-controller", {true, "string", false}}, // tuic
        {"cwnd", {true, "int", false}}, // tuic
        {"dialer-proxy", {true, "string", false}}, // BasicOption
        {"disable-mtu-discovery", {true, "bool", false}}, // tuic
        {"disable-sni", {true, "bool", true}}, // tuic [HARDCODED]
        {"ech-opts", {true, "string", false}}, // tuic
        {"fast-open", {true, "bool", false}}, // tuic
        {"fingerprint", {true, "string", false}}, // tuic
        {"heartbeat-interval", {true, "int", false}}, // tuic
        {"interface-name", {true, "string", false}}, // BasicOption
        {"ip", {true, "string", false}}, // tuic
        {"ip-version", {true, "string", false}}, // BasicOption
        {"max-datagram-frame-size", {true, "int", false}}, // tuic
        {"max-open-streams", {true, "int", false}}, // tuic
        {"max-udp-relay-packet-size", {true, "int", false}}, // tuic
        {"mptcp", {true, "bool", false}}, // BasicOption
        {"name", {true, "string", false}}, // tuic
        {"password", {true, "string", false}}, // tuic
        {"port", {true, "int", false}}, // tuic
        {"private-key", {true, "string", false}}, // tuic
        {"recv-window", {true, "int", false}}, // tuic
        {"recv-window-conn", {true, "int", false}}, // tuic
        {"reduce-rtt", {true, "bool", false}}, // tuic
        {"request-timeout", {true, "int", false}}, // tuic
        {"routing-mark", {true, "int", false}}, // BasicOption
        {"server", {true, "string", false}}, // tuic
        {"skip-cert-verify", {true, "bool", false}}, // tuic
        {"sni", {true, "string", false}}, // tuic
        {"tfo", {true, "bool", false}}, // BasicOption
        {"token", {true, "string", false}}, // tuic
        {"udp-over-stream", {true, "bool", false}}, // tuic
        {"udp-over-stream-version", {true, "int", false}}, // tuic
        {"udp-relay-mode", {true, "string", false}}, // tuic
        {"uuid", {true, "string", false}}, // tuic
    }},
    // Protocol: vless
    {"vless", {
        {"alpn", {true, "array", false}}, // vless
        {"certificate", {true, "string", false}}, // vless
        {"client-fingerprint", {true, "string", false}}, // vless
        {"dialer-proxy", {true, "string", false}}, // BasicOption
        {"ech-opts", {true, "string", false}}, // vless
        {"encryption", {true, "string", false}}, // vless
        {"fingerprint", {true, "string", false}}, // vless
        {"flow", {true, "string", false}}, // vless
        {"grpc-opts", {true, "string", false}}, // vless
        {"h2-opts", {true, "string", false}}, // vless
        {"http-opts", {true, "string", false}}, // vless
        {"interface-name", {true, "string", false}}, // BasicOption
        {"ip-version", {true, "string", false}}, // BasicOption
        {"mptcp", {true, "bool", false}}, // BasicOption
        {"name", {true, "string", false}}, // vless
        {"network", {true, "string", false}}, // vless
        {"packet-addr", {true, "bool", false}}, // vless
        {"packet-encoding", {true, "string", false}}, // vless
        {"port", {true, "int", false}}, // vless
        {"private-key", {true, "string", false}}, // vless
        {"reality-opts", {true, "string", false}}, // vless
        {"routing-mark", {true, "int", false}}, // BasicOption
        {"server", {true, "string", false}}, // vless
        {"servername", {true, "string", false}}, // vless
        {"skip-cert-verify", {true, "bool", false}}, // vless
        {"tfo", {true, "bool", false}}, // BasicOption
        {"tls", {true, "bool", false}}, // vless
        {"udp", {true, "bool", false}}, // vless
        {"uuid", {true, "string", false}}, // vless
        {"ws-headers", {true, "object", false}}, // vless
        {"ws-opts", {true, "string", false}}, // vless
        {"xudp", {true, "bool", false}}, // vless
    }},
    // Protocol: vmess
    {"vmess", {
        {"alpn", {true, "array", false}}, // vmess
        {"alterId", {true, "int", true}}, // vmess [HARDCODED]
        {"authenticated-length", {true, "bool", false}}, // vmess
        {"certificate", {true, "string", false}}, // vmess
        {"cipher", {true, "string", true}}, // vmess [HARDCODED]
        {"client-fingerprint", {true, "string", false}}, // vmess
        {"dialer-proxy", {true, "string", false}}, // BasicOption
        {"ech-opts", {true, "string", false}}, // vmess
        {"fingerprint", {true, "string", false}}, // vmess
        {"global-padding", {true, "bool", false}}, // vmess
        {"grpc-opts", {true, "string", false}}, // vmess
        {"h2-opts", {true, "string", false}}, // vmess
        {"http-opts", {true, "string", false}}, // vmess
        {"interface-name", {true, "string", false}}, // BasicOption
        {"ip-version", {true, "string", false}}, // BasicOption
        {"mptcp", {true, "bool", false}}, // BasicOption
        {"name", {true, "string", false}}, // vmess
        {"network", {true, "string", false}}, // vmess
        {"packet-addr", {true, "bool", false}}, // vmess
        {"packet-encoding", {true, "string", false}}, // vmess
        {"port", {true, "int", false}}, // vmess
        {"private-key", {true, "string", false}}, // vmess
        {"reality-opts", {true, "string", false}}, // vmess
        {"routing-mark", {true, "int", false}}, // BasicOption
        {"server", {true, "string", false}}, // vmess
        {"servername", {true, "string", false}}, // vmess
        {"skip-cert-verify", {true, "bool", true}}, // vmess [HARDCODED]
        {"tfo", {true, "bool", false}}, // BasicOption
        {"tls", {true, "bool", true}}, // vmess [HARDCODED]
        {"udp", {true, "bool", true}}, // vmess [HARDCODED]
        {"uuid", {true, "string", false}}, // vmess
        {"ws-opts", {true, "string", false}}, // vmess
        {"xudp", {true, "bool", true}}, // vmess [HARDCODED]
    }},
};

// Check if a protocol supports a specific parameter
inline bool isParamSupported(const std::string& protocol, const std::string& param) {
    auto proto_it = PARAM_COMPAT.find(protocol);
    if (proto_it == PARAM_COMPAT.end()) return false;
    auto param_it = proto_it->second.find(param);
    return param_it != proto_it->second.end() && param_it->second.supported;
}

// Check if a parameter is hardcoded by Mihomo for this protocol
// Hardcoded parameters should NOT be overridden by global settings
inline bool isParamHardcoded(const std::string& protocol, const std::string& param) {
    auto proto_it = PARAM_COMPAT.find(protocol);
    if (proto_it == PARAM_COMPAT.end()) return false;
    auto param_it = proto_it->second.find(param);
    return param_it != proto_it->second.end() && param_it->second.hardcoded;
}

} // namespace mihomo
