#!/usr/bin/env bash
set -euo pipefail

: "${THREADS:?THREADS is required}"
: "${SHA:?SHA is required}"
: "${VERSION:?VERSION is required}"
: "${BUILD_DATE:?BUILD_DATE is required}"

MIHOMO_REF="${MIHOMO_REF:-Meta}"
MIHOMO_CACHE_BUST="${MIHOMO_CACHE_BUST:-stable}"
SOURCE_DEPS_CACHE_BUST="${SOURCE_DEPS_CACHE_BUST:-stable}"
REFRESH_GO_DEPS="${REFRESH_GO_DEPS:-false}"
REFRESH_HEADERS="${REFRESH_HEADERS:-false}"

cat <<EOF
THREADS=${THREADS}
SHA=${SHA}
VERSION=${VERSION}
BUILD_DATE=${BUILD_DATE}
MIHOMO_REF=${MIHOMO_REF}
MIHOMO_CACHE_BUST=${MIHOMO_CACHE_BUST}
SOURCE_DEPS_CACHE_BUST=${SOURCE_DEPS_CACHE_BUST}
REFRESH_GO_DEPS=${REFRESH_GO_DEPS}
REFRESH_HEADERS=${REFRESH_HEADERS}
EOF
